[package]
name = "sombra-python"
version = "0.4.0"
edition = "2021"
description = "Python bindings for Sombra graph database"
license = "MIT"
repository = "https://github.com/maskdotdev/sombra"

[lib]
name = "sombra"
crate-type = ["cdylib"]

[dependencies]
sombra = { path = "../core" }
pyo3 = { version = "0.27", features = ["extension-module"] }
parking_lot = "0.12"
