[package]
name = "sombradb"

[build]
targets = ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "aarch64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf"]

[build.dynamic]
crt-static = false