[package]
name = "sombra"
version = "0.3.6"
edition = "2021"
description = "High-performance graph database with ACID transactions, single-file storage, and bindings for Rust, TypeScript, and Python"
license = "MIT"
repository = "https://github.com/maskdotdev/sombra"
documentation = "https://docs.rs/sombra"
keywords = ["graph", "database", "graph-database", "acid", "transactions"]
categories = ["database-implementations", "data-structures"]

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
crc32fast = "1.4"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = { version = "3.10", optional = true }
rand = { version = "0.8", optional = true }
clap = { version = "4.0", optional = true }
rusqlite = { version = "0.31", optional = true }
base64 = { version = "0.22", optional = true }
tokio = { version = "1.0", features = ["full"], optional = true }
chrono = "0.4"
lru = "0.12"
dashmap = "5.5"
memmap2 = "0.9"
parking_lot = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
rayon = "1.7"
fs2 = "0.4"

[features]
default = ["cli"]
cli = []
benchmarks = ["dep:tempfile", "dep:rand", "dep:rusqlite", "dep:base64", "dep:clap", "dep:tokio"]

[[bin]]
name = "sombra"
path = "src/bin/sombra.rs"
required-features = ["cli"]

[[bin]]
name = "sombra-inspect"
required-features = ["benchmarks", "cli"]

[[bin]]
name = "sombra-repair"
required-features = ["benchmarks", "cli"]

[[bin]]
name = "sombra-verify"
path = "src/bin/sombra-verify.rs"
required-features = ["cli"]

[[bench]]
name = "benchmark_main"
harness = false

[[bench]]
name = "read_benchmark"
harness = false

[[bench]]
name = "scalability_benchmark"
harness = false

[[bench]]
name = "index_benchmark"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "btree_enhancement_benchmark"
harness = false

[[bench]]
name = "simple_read_benchmark"
harness = false

[[bench]]
name = "optimization_benchmark"
harness = false

[[bench]]
name = "quick_read_test"
harness = false

[[bench]]
name = "small_read_benchmark"
harness = false

[[bench]]
name = "traversal_benchmark"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "concurrency_benchmark"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "property_update_benchmark"
harness = false

[[bench]]
name = "btree_benchmark"
harness = false

[[bench]]
name = "mvcc_performance"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "mvcc_criterion"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "mvcc_simple_criterion"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "mvcc_profile"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "mvcc_detailed_profile"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "concurrent_throughput"
harness = false
required-features = ["benchmarks"]

[[bench]]
name = "lock_contention_profile"
harness = false
required-features = ["benchmarks"]

[[example]]
name = "social_graph"

[[example]]
name = "code_analysis"

[[example]]
name = "transaction_handling"

[dev-dependencies]
proptest = "1.0"
tempfile = "3.10"
rand = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }
