/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DatabaseHandle {

}

export declare class StreamHandle {
  next(): NapiResult<any | undefined | null>
}

export interface BfsTraversalOptions {
  direction?: string
  edgeTypes?: Array<string>
  maxResults?: number
}

export interface BfsVisitRecord {
  nodeId: number
  depth: number
}

export interface ConnectOptions {
  createIfMissing?: boolean
  pageSize?: number
  cachePages?: number
  distinctNeighborsDefault?: boolean
  synchronous?: string
  commitCoalesceMs?: number
  commitMaxFrames?: number
  commitMaxCommits?: number
  groupCommitMaxWriters?: number
  groupCommitMaxFrames?: number
  groupCommitMaxWaitMs?: number
  asyncFsync?: boolean
  asyncFsyncMaxWaitMs?: number
  walSegmentBytes?: number
  walPreallocateSegments?: number
  autocheckpointMs?: number
}

export declare function databaseBfsTraversal(handle: DatabaseHandle, startId: number, maxDepth: number, options?: BfsTraversalOptions | undefined | null): NapiResult<Array<BfsVisitRecord>>

export declare function databaseCancelRequest(handle: DatabaseHandle, requestId: string): NapiResult<boolean>

/**
 * Closes the database handle, releasing all resources.
 *
 * After calling close(), all subsequent operations on this handle will fail
 * with a "database is closed" error.
 */
export declare function databaseClose(handle: DatabaseHandle): NapiResult<undefined>

export declare function databaseCountEdgesWithType(handle: DatabaseHandle, ty: string): NapiResult<bigint>

export declare function databaseCountNodesWithLabel(handle: DatabaseHandle, label: string): NapiResult<bigint>

export declare function databaseCreate(handle: DatabaseHandle, spec: any): NapiResult<any>

export declare function databaseExecute(handle: DatabaseHandle, spec: any): NapiResult<any>

export declare function databaseExplain(handle: DatabaseHandle, spec: any): NapiResult<any>

export declare function databaseGetEdge(handle: DatabaseHandle, edgeId: number): NapiResult<any | undefined | null>

export declare function databaseGetNode(handle: DatabaseHandle, nodeId: number): NapiResult<any | undefined | null>

export declare function databaseIntern(handle: DatabaseHandle, name: string): NapiResult<number>

export declare function databaseListNodesWithLabel(handle: DatabaseHandle, label: string): NapiResult<Array<bigint>>

export declare function databaseMutate(handle: DatabaseHandle, spec: any): NapiResult<any>

export declare function databaseNeighbors(handle: DatabaseHandle, nodeId: number, options?: NeighborOptions | undefined | null): NapiResult<Array<NeighborRecord>>

export declare function databasePragmaGet(handle: DatabaseHandle, name: string): NapiResult<any>

export declare function databasePragmaSet(handle: DatabaseHandle, name: string, value: any): NapiResult<any>

export declare function databaseSeedDemo(handle: DatabaseHandle): NapiResult<undefined>

export declare function databaseStream(handle: DatabaseHandle, spec: any): NapiResult<StreamHandle>

export interface NeighborOptions {
  direction?: string
  edgeType?: string
  distinct?: boolean
}

export interface NeighborRecord {
  nodeId: number
  edgeId: number
  typeId: number
}

export declare function openDatabase(path: string, options?: ConnectOptions | undefined | null): NapiResult<DatabaseHandle>
