/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DatabaseHandle {

}

export declare class StreamHandle {
  next(): NapiResult<any | undefined | null>
}

export interface ConnectOptions {
  createIfMissing?: boolean
  pageSize?: number
  cachePages?: number
  distinctNeighborsDefault?: boolean
  synchronous?: string
  commitCoalesceMs?: number
  commitMaxFrames?: number
  commitMaxCommits?: number
  autocheckpointMs?: number
}

export declare function databaseCreate(handle: DatabaseHandle, spec: any): NapiResult<any>

export declare function databaseExecute(handle: DatabaseHandle, spec: any): NapiResult<Array<any>>

export declare function databaseExplain(handle: DatabaseHandle, spec: any): NapiResult<any>

export declare function databaseIntern(handle: DatabaseHandle, name: string): NapiResult<number>

export declare function databaseMutate(handle: DatabaseHandle, spec: any): NapiResult<any>

export declare function databasePragmaGet(handle: DatabaseHandle, name: string): NapiResult<any>

export declare function databasePragmaSet(handle: DatabaseHandle, name: string, value: any): NapiResult<any>

export declare function databaseSeedDemo(handle: DatabaseHandle): NapiResult<undefined>

export declare function databaseStream(handle: DatabaseHandle, spec: any): NapiResult<StreamHandle>

export declare function openDatabase(path: string, options?: ConnectOptions | undefined | null): NapiResult<DatabaseHandle>
