name: Publish CLI Package

# This is a reusable workflow that can be called in two ways:
# 1. Automatically by release-please.yml when a CLI release is created
# 2. Manually via push to tags matching 'cli-v*' (fallback)
#
# The primary trigger is workflow_call from release-please.

on:
  workflow_call:
    inputs:
      tag:
        description: 'Git tag to publish (e.g., cli-v0.1.0)'
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
  push:
    tags:
      - 'cli-v*'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug workflow inputs
        run: |
          echo "=== Workflow Debug Info ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Tag input: ${{ inputs.tag }}"
          echo "Build condition: ${{ inputs.tag != '' || startsWith(github.ref, 'refs/tags/cli-v') }}"

  publish:
    if: |
      inputs.tag != '' || 
      startsWith(github.ref, 'refs/tags/cli-v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag || github.ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: packages/cli/package.json

      - name: Build CLI bundle
        run: |
          cd packages/cli
          bun run build

      - name: Verify package contents
        run: |
          cd packages/cli
          echo "=== Package contents ==="
          npm pack --dry-run
          echo "=== Package.json ==="
          cat package.json

      - name: Publish to npm
        run: |
          cd packages/cli
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify publish
        run: |
          echo "✅ @unyth/sombra-cli published successfully"
          echo "Tag: ${{ inputs.tag || github.ref }}"
          echo "View at: https://www.npmjs.com/package/@unyth/sombra-cli"
